# params settings
params:

# logging settings
logging:
  config: classpath:config/logback-spring.xml
  log-dir: /var/log/dataroute

# mybatis settings
mybatis:
  check-config-location: true
  config-location: classpath:config/mybatis-config.xml

# spring settings
spring:
  application:
    name: dataroute
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.27:3306/lk_test?characterEncoding=UTF-8
    username: root
    password: oec!Server
    hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        max-lifetime: 30000
        connection-test-query: SELECT 1

# server settings
server:
  port: 9081
  servlet:
    context-path: /dataroute
    session:
      timeout: 30
  tomcat:
    uri-encoding: utf-8
    max-threads: 0
